### ISSUE TITLE
Error CSSharp v188

### ISSUE THREAD

**Issue by umbr1X** [Iksix/NameChecker-cs2#1]
16:53:31 [EROR] (cssharp:PluginManager) Failed to load plugin from csgo/addons/counterstrikesharp/plugins/NameChecker/NameChecker.dll
System.Exception: Unable to find plugin in assembly
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 131
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 122
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 91

**Comment by Mraduu** [comment]
it needs to be made update on framework/api with the new sharp changes

**Comment by GreathostRo** [comment]
Update please to Work on CounterStrikeSharp v194

**Comment by Iksix** [comment]
Guys, I know about this problem, I just don't have time to solve it. A simple rebuild didn't help, so we need to figure it out.

**Comment by Iksix** [comment]
I finally fixed it.
